image: python:2.7

stages:
 - test

before_script:
  - "pip install -U platformio"

job:
  stage: test
  script: "platformio ci --project-conf platformio.ini --lib 'lib/dht22'"
  variables: {PLATFORMIO_CI_SRC: "src"}
